services:
# TODO: springbootのコンテナの設定を追加する。environment:DB_PASSWORD=rootpassを忘れず
# DB設定などについては.envなどに括りだし、.gitignoreに追加することでgithubに公開されないようにすることが望ましいが、今回はデプロイ手順を簡単にして手軽に手元で試してもらえるようにするため、あえて直書きしている。
  mariadb:
    image: mariadb:11
    container_name: mariadb

    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: counseling-reservation-system-db
      MYSQL_USER: user1
      MYSQL_PASSWORD: userpass

    ports:
      - "3306:3306"

    volumes:
      - mariadb_data:/var/lib/mysql

    restart: unless-stopped

volumes:
  mariadb_data:
