spring:
  application:
    name: CounselingReservationSystem
  datasource:
    url: jdbc:mysql://localhost:3306/counseling-reservation-system-db
    username: root
    # password: ${DB_PASSWORD} TODO: 現状docker composeではなくeclipseからテストするためパスワードを直書きしている。docker composeでテストする場合はコメントアウトして、環境変数DB_PASSWORDを設定すること。
    password: rootpass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      data-locations: 
        - classpath:/sql/users.sql
        - classpath:/sql/slot_templates.sql

# デバッグ用 TODO:リリーズ時に消す
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
