spring:
  application:
    name: CounselingReservationSystem
  datasource:
    url: jdbc:mysql://localhost:3306/counseling-reservation-system-db
    username: root
    password: ${DB_PASSWORD} 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      data-location: 
        - classpath:/sql/users.sql
        - classpath:/sql/slot_templates.sql

